import type { AppModuleDefinition } from "@/shared/modules/types";

export const dovrutModule: AppModuleDefinition = {
  id: "dovrut",
  label: "דוברות",
  description: "קמפיינים, פרויקטים, אייטמים וציר אישורים",
  href: "/dovrut",
  navItems: [
    { label: "ראשי", href: "/dovrut", description: "סקירת דוברות", roles: ["admin", "user", "viewer"] },
    {
      label: "קמפיינים",
      href: "/dovrut/campaigns",
      description: "קמפיינים תקשורתיים",
      roles: ["admin", "user", "viewer"],
    },
    {
      label: "פרויקטים",
      href: "/dovrut/projects",
      description: "פרויקטים תחת קמפיינים",
      roles: ["admin", "user", "viewer"],
    },
    {
      label: "ארכיון פרויקטים",
      href: "/dovrut/projects/archive",
      description: "פרויקטים שהסתיימו",
      roles: ["admin", "user", "viewer"],
    },
    {
      label: "סל מחזור",
      href: "/dovrut/recycle-bin",
      description: "שחזור ומחיקה לצמיתות",
      roles: ["admin", "user"],
    },
    {
      label: "אייטמים",
      href: "/dovrut/items",
      description: "כתבות ורשתות",
      roles: ["admin", "user", "viewer"],
    },
    {
      label: "גורמי תחקורים",
      href: "/dovrut/inquiry-subjects",
      description: "כרטיסי רקע לתדרוך ותחקור",
      roles: ["admin", "user", "viewer"],
    },
    {
      label: "משימות כלליות",
      href: "/dovrut/tasks",
      description: "משימות שנוצרו בדוברות",
      roles: ["admin", "user", "viewer"],
    },
    {
      label: "מסרים",
      href: "/dovrut/audiences",
      description: "מסרים לפי קהל יעד ותחום",
      roles: ["admin", "user", "viewer"],
    },
    {
      label: "חיפוש חדשות",
      href: "/dovrut/news",
      description: "חיפוש בגוגל חדשות",
      roles: ["admin", "user", "viewer"],
    },
    {
      label: "אישורי אייטמים",
      href: "/dovrut/approvals",
      description: "תור אישורים לפי שלב",
      roles: ["admin", "user", "approver"],
    },
  ],
  adminNavItems: [
    {
      label: "משתמשים",
      href: "/dovrut/admin/users",
      description: "ניהול משתמשים, אפליקציות והרשאות",
    },
    {
      label: "ניהול מאשרים",
      href: "/dovrut/admin/approvers",
      description: "תזכורות אישור בטלגרם",
    },
  ],
  breadcrumbLabels: {
    dovrut: "דוברות",
    campaigns: "קמפיינים",
    projects: "פרויקטים",
    concepts: "אייטמים",
    items: "אייטמים",
    "inquiry-subjects": "גורמי תחקורים",
    tasks: "משימות כלליות",
    audiences: "מסרים",
    news: "חדשות",
    approvals: "אישורי אייטמים",
    approval: "אישור",
    "branch-head": "רמ״ח",
    "deputy-commander": "רמ״ט",
    "chief-rabbi": "רבצ״ר",
    archive: "ארכיון",
    "recycle-bin": "סל מחזור",
    admin: "ניהול",
    users: "משתמשים",
    approvers: "מאשרים",
  },
};
